inputs:
  APPLICATION_VERSION:
    required: true
  CONTAINER_IMAGE_NAME:
    required: true
  CONTAINER_REGISTRY_REGION:
    required: true
  CONTAINER_REGISTRY_URL:
    required: true
  DOCKERFILE_PATH:
    required: true
  GOOGLE_PROJECT_ID:
    required: true
  GOOGLE_SERVICE_ACCOUNT_EMAIL:
    required: true

runs:
  using: composite
  steps:
    - name: checkout the repository
      uses: actions/checkout@v4

    - name: build the service
      shell: bash
      run: docker build . --file ${{ inputs.DOCKERFILE_PATH }} --tag ${{ inputs.CONTAINER_REGISTRY_URL }}/${{ inputs.CONTAINER_IMAGE_NAME }}:${{ inputs.APPLICATION_VERSION }}

    - name: publish the service (google authentication)
      id: authentication-google
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: projects/${{ inputs.GOOGLE_PROJECT_ID }}/locations/global/workloadIdentityPools/github/providers/github
        service_account: ${{ inputs.GOOGLE_SERVICE_ACCOUNT_EMAIL }}

    - name: publish the service (docker login)
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.CONTAINER_REGISTRY_URL }}
        username: oauth2accesstoken
        password: ${{ steps.authentication-google.outputs.access_token }}

    - name: publish the service (docker push)
      shell: bash
      run: docker push ${{ inputs.CONTAINER_REGISTRY_URL }}/${{ inputs.CONTAINER_IMAGE_NAME }} --all-tags

    - name: publish the service (cloudrun deploy)
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: service
        region: ${{ inputs.CONTAINER_REGISTRY_REGION }}
        image: ${{ inputs.CONTAINER_REGISTRY_URL }}/${{ inputs.CONTAINER_IMAGE_NAME }}:${{ inputs.APPLICATION_VERSION }}
